// Generated by scripts/build_data.sh — do not edit by hand.
// Source: ONS Dados Abertos (constrained-off eólica & fotovoltaica).
window.ONS_DATA = {
  "generated": "2026-06-19 21:10",
  "range": {"start": "2026-01", "end": "2026-03"},
  "unit": "GWh",
  "kpi": {"wind": 3730.5, "solar": 1922.5, "total": 5653.0},
  "monthly": [{"month":"2026-01","wind":2405.8,"solar":733.3},{"month":"2026-02","wind":492.7,"solar":336.0},{"month":"2026-03","wind":832.0,"solar":853.2}],
  "subsystem": [{"name":"NORDESTE","wind":3666.6,"solar":1073.9},{"name":"SUDESTE/CENTRO-OESTE","wind":6.0,"solar":848.7},{"name":"NORTE","wind":31.2,"solar":0.0},{"name":"SUL","wind":26.7,"solar":0.0}],
  "reasons": [{"code":"ENE","wind":1779.7,"solar":1337.4},{"code":"CNF","wind":1211.7,"solar":406.2},{"code":"REL","wind":739.0,"solar":179.0}],
  "states": [{"uf":"BA","name":"BAHIA","total":1866.6},{"uf":"PI","name":"PIAUI","total":531.3},{"uf":"CE","name":"CEARA","total":517.9},{"uf":"PE","name":"PERNAMBUCO","total":210.9},{"uf":"PB","name":"PARAIBA","total":102.8},{"uf":"MA","name":"MARANHAO","total":31.2},{"uf":"GO","name":"GOIAS","total":4.4},{"uf":"SP","name":"SAO","total":0.0},{"uf":"SC","name":"SANTA","total":0.0},{"uf":"RS","name":"RIO","total":0.0}]
};
