// Generated by bpcm.export_dashboard — do not edit by hand.
// Source: ONS Dados Abertos via the bpcm warehouse.
window.ONS_DATA = {
  "generated": "2026-06-19 23:49",
  "range": {
    "start": "2026-03",
    "end": "2026-03"
  },
  "unit": "GWh",
  "kpi": {
    "wind": 832.0,
    "solar": 853.2,
    "total": 1685.3,
    "rate_pct": 15.5
  },
  "monthly": [
    {
      "month": "2026-03",
      "wind": 832.0,
      "solar": 853.2
    }
  ],
  "subsystem": [
    {
      "name": "NORDESTE",
      "wind": 812.6,
      "solar": 462.3
    },
    {
      "name": "SUDESTE/CENTRO-OESTE",
      "wind": 2.3,
      "solar": 390.9
    },
    {
      "name": "NORTE",
      "wind": 13.9,
      "solar": 0.0
    },
    {
      "name": "SUL",
      "wind": 3.2,
      "solar": 0.0
    }
  ],
  "reasons": [
    {
      "code": "ENE",
      "wind": 710.9,
      "solar": 728.8
    },
    {
      "code": "CNF",
      "wind": 65.0,
      "solar": 59.3
    },
    {
      "code": "REL",
      "wind": 56.1,
      "solar": 65.1
    }
  ],
  "states": [
    {
      "uf": "BA",
      "name": "BAHIA",
      "total": 433.4
    },
    {
      "uf": "RN",
      "name": "RIO GRANDE DO NORTE",
      "total": 355.7
    },
    {
      "uf": "MG",
      "name": "MINAS GERAIS",
      "total": 335.7
    },
    {
      "uf": "PI",
      "name": "PIAUI",
      "total": 214.1
    },
    {
      "uf": "CE",
      "name": "CEARA",
      "total": 160.1
    },
    {
      "uf": "PE",
      "name": "PERNAMBUCO",
      "total": 78.0
    },
    {
      "uf": "SP",
      "name": "SAO PAULO",
      "total": 50.8
    },
    {
      "uf": "PB",
      "name": "PARAIBA",
      "total": 36.0
    },
    {
      "uf": "MA",
      "name": "MARANHAO",
      "total": 13.9
    },
    {
      "uf": "GO",
      "name": "GOIAS",
      "total": 4.4
    }
  ]
};
