"""Export the mart to dashboard/data.js (window.ONS_DATA) for the static dashboard.

Produces the same shape the existing dashboard expects (kpi/monthly/subsystem/
reasons/states, in GWh) plus an overall curtailment rate.
"""
from __future__ import annotations

import json
from datetime import datetime

import duckdb

from . import config

log = config.get_logger("export")

MART = config.MARTS / "mart_plant_monthly.parquet"


def _curt_expr() -> str:
    return ("GREATEST(0, COALESCE(TRY_CAST(val_geracaoreferenciafinal AS DOUBLE),"
            " TRY_CAST(val_geracaoreferencia AS DOUBLE), 0)"
            " - COALESCE(TRY_CAST(val_geracao AS DOUBLE), 0)) * 0.5")


def export() -> dict:
    con = duckdb.connect()
    t = f"read_parquet('{MART}')"

    # KPIs (GWh) + overall rate
    wind = con.execute(f"SELECT COALESCE(SUM(curtailed_mwh),0)/1000 FROM {t} WHERE source='wind'").fetchone()[0]
    solar = con.execute(f"SELECT COALESCE(SUM(curtailed_mwh),0)/1000 FROM {t} WHERE source='solar'").fetchone()[0]
    rate = con.execute(
        f"SELECT CASE WHEN SUM(gen_observed_mwh)+SUM(curtailed_mwh) > 0 "
        f"THEN SUM(curtailed_mwh)/(SUM(gen_observed_mwh)+SUM(curtailed_mwh)) ELSE NULL END FROM {t}"
    ).fetchone()[0]

    monthly = con.execute(f"""
        SELECT month,
               COALESCE(SUM(curtailed_mwh) FILTER (WHERE source='wind'),0)/1000,
               COALESCE(SUM(curtailed_mwh) FILTER (WHERE source='solar'),0)/1000
        FROM {t} GROUP BY month ORDER BY month
    """).fetchall()

    subsystem = con.execute(f"""
        SELECT COALESCE(subsystem_name,'?'),
               COALESCE(SUM(curtailed_mwh) FILTER (WHERE source='wind'),0)/1000,
               COALESCE(SUM(curtailed_mwh) FILTER (WHERE source='solar'),0)/1000
        FROM {t} GROUP BY 1 ORDER BY (SUM(curtailed_mwh)) DESC
    """).fetchall()

    states = con.execute(f"""
        SELECT COALESCE(uf,'?'), COALESCE(uf_name,'?'), SUM(curtailed_mwh)/1000 AS gwh
        FROM {t} GROUP BY 1,2 ORDER BY gwh DESC LIMIT 10
    """).fetchall()

    # Reasons come from staging (the mart does not carry reason codes)
    arms = []
    for src, name in (("wind", "ons.curtailment_wind"), ("solar", "ons.curtailment_solar")):
        d = config.STAGING / name
        if d.exists() and any(d.glob("*.parquet")):
            arms.append(f"SELECT '{src}' AS source, cod_razaorestricao AS code, {_curt_expr()} AS mwh "
                        f"FROM read_parquet('{d}/*.parquet', union_by_name=true) "
                        f"WHERE cod_razaorestricao IS NOT NULL AND cod_razaorestricao <> ''")
    reasons = []
    if arms:
        reasons = con.execute(f"""
            WITH r AS ({' UNION ALL BY NAME '.join(arms)})
            SELECT code,
                   COALESCE(SUM(mwh) FILTER (WHERE source='wind'),0)/1000,
                   COALESCE(SUM(mwh) FILTER (WHERE source='solar'),0)/1000
            FROM r GROUP BY code ORDER BY SUM(mwh) DESC
        """).fetchall()

    con.close()

    months = [m[0] for m in monthly]
    data = {
        "generated": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "range": {"start": months[0] if months else None, "end": months[-1] if months else None},
        "unit": "GWh",
        "kpi": {"wind": round(wind, 1), "solar": round(solar, 1), "total": round(wind + solar, 1),
                "rate_pct": round(rate * 100, 1) if rate is not None else None},
        "monthly": [{"month": m, "wind": round(w, 1), "solar": round(s, 1)} for m, w, s in monthly],
        "subsystem": [{"name": n, "wind": round(w, 1), "solar": round(s, 1)} for n, w, s in subsystem],
        "reasons": [{"code": c, "wind": round(w, 1), "solar": round(s, 1)} for c, w, s in reasons],
        "states": [{"uf": uf, "name": nm, "total": round(g, 1)} for uf, nm, g in states],
    }

    out = config.DASHBOARD / "data.js"
    out.write_text(
        "// Generated by bpcm.export_dashboard — do not edit by hand.\n"
        "// Source: ONS Dados Abertos via the bpcm warehouse.\n"
        "window.ONS_DATA = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n"
    )
    log.info("wrote   %s | total %.1f GWh | rate %s%%", out, data["kpi"]["total"], data["kpi"]["rate_pct"])
    return data
